services:
  mysqldb:
    image: "mysql:latest"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=userinfo
    networks:
      - my-network
    container_name: "mysqldb"
    healthcheck:
      test: ["CMD", "mysqladmin","ping", "-h", "localhost"]
      interval: 1m30s
      timeout: 20s
      retries: 5
      start_period: 30s

  mypythonapp:
    build: ./
    container_name: mypythonapp
    networks:
      - my-network
    volumes:
      - ./servers.txt:/myapp/services.txt
    depends_on:
      mysqldb:
        condition: service_healthy
    stdin_open: true
    tty: true
  
networks:
  my-network: